version: '3.9'

services:

  backend:
    build: ./backend
    command: sh -c "node create-tables.js && node create-admin.js && npm start"
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: rf_event
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rf_event
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000/api
    ports:
      - "3000:80"
    depends_on:
      - backend

  admin-app:
    build:
      context: ./admin-app
      args:
        VITE_ADMIN_API_URL: http://localhost:5000/api/admin
    ports:
      - "3001:80"
    depends_on:
      - backend
